"""Helpers for planning directory creation and permission reconciliation."""
from __future__ import annotations

import grp
import os
import pwd
import shutil
import stat
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal


@dataclass(slots=True)
class DirectorySpec:
    """Desired state for a directory in the bootstrap process."""

    path: Path
    owner: str | None = None
    group: str | None = None
    mode: int | None = None
    parents: bool = True


@dataclass(slots=True)
class DirectoryState:
    """Observed state of a directory on disk."""

    exists: bool
    is_directory: bool
    owner: str | None
    group: str | None
    mode: int | None


@dataclass(slots=True)
class DirectoryAction:
    """Single filesystem operation required to meet a directory spec."""

    kind: Literal["mkdir", "chown", "chmod"]
    path: Path
    owner: str | None = None
    group: str | None = None
    mode: int | None = None
    parents: bool = False


@dataclass(slots=True)
class DirectoryPlan:
    """Collection of actions and warnings needed to satisfy directory specs."""

    actions: list[DirectoryAction] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


def _stat_directory(path: Path) -> DirectoryState:
    try:
        info = path.stat()
    except FileNotFoundError:
        return DirectoryState(
            exists=False,
            is_directory=False,
            owner=None,
            group=None,
            mode=None,
        )
    is_directory = stat.S_ISDIR(info.st_mode)
    try:
        owner = pwd.getpwuid(info.st_uid).pw_name
    except KeyError:
        owner = None
    try:
        group = grp.getgrgid(info.st_gid).gr_name
    except KeyError:
        group = None
    mode = info.st_mode & 0o777
    return DirectoryState(
        exists=True,
        is_directory=is_directory,
        owner=owner,
        group=group,
        mode=mode,
    )


def plan_directories(specs: list[DirectorySpec]) -> DirectoryPlan:
    """Return the actions required to satisfy *specs*."""
    plan = DirectoryPlan()
    for spec in specs:
        state = _stat_directory(spec.path)
        if state.exists and not state.is_directory:
            plan.warnings.append(f"{spec.path} exists but is not a directory.")
            continue
        if not state.exists:
            plan.actions.append(
                DirectoryAction(
                    kind="mkdir",
                    path=spec.path,
                    mode=spec.mode,
                    owner=spec.owner,
                    group=spec.group,
                    parents=spec.parents,
                )
            )
            continue
        if spec.owner and spec.owner != state.owner:
            plan.actions.append(
                DirectoryAction(
                    kind="chown",
                    path=spec.path,
                    owner=spec.owner,
                    group=spec.group or state.group,
                )
            )
        elif spec.group and spec.group != state.group:
            plan.actions.append(
                DirectoryAction(
                    kind="chown",
                    path=spec.path,
                    owner=state.owner,
                    group=spec.group,
                )
            )
        if spec.mode is not None and spec.mode != state.mode:
            plan.actions.append(
                DirectoryAction(
                    kind="chmod",
                    path=spec.path,
                    mode=spec.mode,
                )
            )
    return plan


def apply_directory_plan(plan: DirectoryPlan, *, dry_run: bool = False) -> None:
    """Apply actions generated by :func:`plan_directories`."""
    for action in plan.actions:
        if dry_run:
            continue
        if action.kind == "mkdir":
            action.path.mkdir(mode=action.mode or 0o755, parents=action.parents, exist_ok=True)
            if action.owner is not None or action.group is not None:
                mkdir_chown_kwargs: dict[str, str] = {}
                if action.owner is not None:
                    mkdir_chown_kwargs["user"] = action.owner
                if action.group is not None:
                    mkdir_chown_kwargs["group"] = action.group
                shutil.chown(action.path, **mkdir_chown_kwargs)
            if action.mode is not None:
                os.chmod(action.path, action.mode)
        elif action.kind == "chown":
            chown_kwargs: dict[str, str] = {}
            if action.owner is not None:
                chown_kwargs["user"] = action.owner
            if action.group is not None:
                chown_kwargs["group"] = action.group
            shutil.chown(action.path, **chown_kwargs)
        elif action.kind == "chmod" and action.mode is not None:
            os.chmod(action.path, action.mode)


__all__ = [
    "DirectoryAction",
    "DirectoryPlan",
    "DirectorySpec",
    "apply_directory_plan",
    "plan_directories",
]
