name: CI

on:
  push:
    branches: [main, dev, "dev-*"]
  pull_request:
    branches: [main, dev, "dev-*"]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev]

      - name: Lint with Ruff
        run: ruff check src tests

      - name: Type-check with mypy
        run: mypy src

      - name: Run tests
        run: pytest --cov=abssctl --cov-report=term-missing

      - name: Build documentation
        run: sphinx-build -b html docs/source docs/_build/html
