name: Publish Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  id-token: write

concurrency:
  group: publish-release-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  publish-release:
    if: "!endsWith(github.ref_name, '-dev')"
    runs-on: ubuntu-latest
    environment: publish-release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure tag points at main
        run: |
          TAG_COMMIT=$(git rev-parse $GITHUB_SHA)
          MAIN_COMMIT=$(git rev-parse origin/main)
          if ! git merge-base --is-ancestor $MAIN_COMMIT $TAG_COMMIT; then
            echo "Tag is not on main. Exiting."
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Validate release tag version
        run: |
          TAG="${GITHUB_REF_NAME}"
          if [[ "${TAG}" != v* ]]; then
            echo "Release workflow triggered for unexpected ref: ${TAG}"
            exit 1
          fi
          if [[ "${TAG}" == *-dev ]]; then
            echo "Release workflow should not run for dev tag: ${TAG}"
            exit 1
          fi
          python3 tools/validate_tag_version.py --kind release --tag "${TAG}"

      - name: Build distributions
        run: |
          make dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.2
